package ca.stewark.helioflux.ui.solaractivity
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import ca.stewark.helioflux.core.data.repository.RepositoryState
import ca.stewark.helioflux.core.model.*
import ca.stewark.helioflux.ui.components.FreshnessIndicator
@Composable fun SolarActivityScreen(state:SolarActivityUiState,expanded:Boolean,onCmeDetails:(CmeEvent)->Unit={},nowMillis:Long=System.currentTimeMillis()){var viewer by remember{mutableStateOf<SolarGalleryItem?>(null)};val chartDomain=solarActivityChartDomain(nowMillis);val regions=(state.activeRegions as? RepositoryState.Available)?.data?:(state.activeRegions as? RepositoryState.Failure)?.retainedData.orEmpty();val freshness=listOf(state.probabilities,state.magnetogram,state.xray,state.flares,state.cmes,state.epam).firstNotNullOfOrNull{(it as? RepositoryState.Available<*>)?.freshness};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Solar Activity",style=MaterialTheme.typography.headlineMedium);freshness?.let{FreshnessIndicator(it)}};FlareProbabilityBadges(state.probabilities);SolarImageryGallery(expanded,state.magnetogram,state.lascoC2,state.lascoC3,regions,state.enlil){viewer=it};val xray=(state.xray as? RepositoryState.Available)?.data?:(state.xray as? RepositoryState.Failure)?.retainedData.orEmpty();XrayChart(xray,chartDomain,Modifier.fillMaxWidth().height(260.dp));val flares=(state.flares as? RepositoryState.Available)?.data?:(state.flares as? RepositoryState.Failure)?.retainedData.orEmpty();FlareList(flares);val cmes=(state.cmes as? RepositoryState.Available)?.data?:(state.cmes as? RepositoryState.Failure)?.retainedData.orEmpty();CmeList(cmes,onCmeDetails);val epam=(state.epam as? RepositoryState.Available)?.data?:(state.epam as? RepositoryState.Failure)?.retainedData.orEmpty();AceEpamChart(epam,chartDomain)};viewer?.let{item->val image=when(item){SolarGalleryItem.Hmi->(state.magnetogram as? RepositoryState.Available)?.data;SolarGalleryItem.LascoC2->(state.lascoC2 as? RepositoryState.Available)?.data;SolarGalleryItem.LascoC3->(state.lascoC3 as? RepositoryState.Available)?.data;SolarGalleryItem.Enlil->null};val enlilUrl=if(item==SolarGalleryItem.Enlil)(state.enlil as? RepositoryState.Available)?.data?.firstOrNull()?.url else null;FullscreenImageryViewer(item.name,image?.url?:enlilUrl,{viewer=null})}}
